### ISSUE TITLE
Strange useless checking

### ISSUE THREAD

**Issue by Enerccio** [bdunn44/MEJS-Vaadin#9]
In setSource there is some strange checking, why can't you just let any resource pass? I am trying to implement external resource to my own handler but can't do it cause you crash with `Only YouTube and Vimeo external resources are allowed` ... why???

**Comment by bdunn44** [comment]
The reasoning behind that is because MEJS only supports hosted video from YouTube and Vimeo. I wrote this a while ago but I also believe that, as written, there might be a MIME type problem if you try to point to an external video file. 

It sounds like that is a bit too limiting in your case, so please do feel free to fork.
